## Importing

In [17]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt

In [2]:
df = pd.read_json('cleaned_data.json')
df.head()

,Name,Address,Author,Price,Bedrooms,Showers,Parking,Furnish,Total Developed,Features,...,Nearby Places,URL,Timestamp,City,Region,Island,Type,NFeatures,NFacilities,NNearby Places
0,"3 BR Condo in The Grand Midori Ortigas, Pasig",,"Federal Land, Inc.",29700000,3,3.0,2,0,107.0,"[Ensuite, Range Hood, Stove/Burner]",...,"[School, Hospital]",https://propertyaccess.ph/property/3-br-condo-...,2022-10-23,Pasig,National Capital Region,Luzon,Condo,3,11,2
1,"1 Bedroom Condo in The Grand Midori Ortigas, P...",,"Federal Land, Inc.",10200000,1,1.0,0,0,46.0,[Fiber ready],...,"[School, Hospital]",https://propertyaccess.ph/property/1br-condo-i...,2022-10-23,Pasig,National Capital Region,Luzon,Condo,1,11,2
2,"3 Bedroom Condo in Aurelia Residences, Taguig","McKinley Parkway, Taguig, Metro Manila",Shang Properties,107300000,3,4.0,2,0,242.0,"[Central air conditioning, Balcony, Built-in w...",...,"[School, Hospital, Mall, Transportation hub]",https://propertyaccess.ph/property/3-bedroom-c...,2022-10-23,Taguig,National Capital Region,Luzon,Condo,10,15,4
3,3 Bedroom Condo in Shang Residences at Wack Wa...,"Wack Wack Road, Mandaluyong, Metro Manila",Shang Properties,54500000,3,4.0,3,0,231.0,"[Central air conditioning, Balcony, Built-in w...",...,"[School, Hospital, Mall, Transportation hub]",https://propertyaccess.ph/property/3-bedroom-c...,2022-10-23,Mandaluyong,National Capital Region,Luzon,Condo,9,16,4
4,"2BR Condo in Residences at The Galleon, Pasig",,Ortigas Land,41500000,2,2.0,2,0,109.0,"[Central air conditioning, Balcony, Built-in w...",...,"[School, Hospital, Mall, Transportation hub]",https://propertyaccess.ph/property/2br-condo-i...,2022-10-23,Pasig,National Capital Region,Luzon,Condo,7,14,4

## Clustering

## RQ 1 [needs visualization]
What is the average price of houses in a given area? (sort by rank)

Answer:

In [59]:
df.groupby(['Type', 'City'])['Price'].mean().sort_values(ascending=False)

Type   City
Condo  Malay                 1.975000e+08
House  Makati                1.290667e+08
       Muntinlupa            9.889375e+07
       Manila                8.944438e+07
       Quezon                6.970911e+07
                                 ...
Condo  San Jose Del Monte    2.200000e+06
House  Cabanatuan            1.927857e+06
       San Jose Del Monte    1.834000e+06
       Mabalacat             1.731500e+06
       Pampanga              1.700000e+06
Name: Price, Length: 103, dtype: float64

In [72]:
df.groupby(['Type', 'Region'])['Price'].mean().sort_values(ascending=False)

Type   Region
Condo  Western Visayas                     6.831117e+07
House  National Capital Region             5.535285e+07
       Cordillera Administrative Region    1.916667e+07
Condo  National Capital Region             1.853212e+07
House   Calabarzon                         1.804468e+07
       Northern Mindanao                   1.535000e+07
Condo  Central Visayas                     1.470068e+07
House  Central Visayas                     1.458560e+07
Condo  Cordillera Administrative Region    1.176154e+07
        Calabarzon                         5.906663e+06
        Ilocos Region                      5.146266e+06
House  Central Luzon                       5.053387e+06
Condo  Northern Mindanao                   3.323333e+06
       Central Luzon                       2.821000e+06
Name: Price, dtype: float64

In [67]:
df.groupby(['Type', 'Island'])['Price'].mean().sort_values(ascending=False)

Type   Island
House  Luzon       4.468048e+07
Condo  Visayas     2.201120e+07
       Luzon       1.769705e+07
House  Mindanao    1.535000e+07
       Visayas     1.458560e+07
Condo  Mindanao    3.323333e+06
Name: Price, dtype: float64

## RQ 2 (don't think this can be answered)
What is the behavior of the price of houses over time? (historical)


Answer:

## RQ 3
Which is the average house price of a given land developer? (sort by rank)

Answer:

In [53]:
df.groupby('Author')['Price'].mean().sort_values(ascending=False)

Author
Baby                 2.500000e+08
Roy                  1.312500e+08
Edwin Chanluangco    1.275000e+08
Darryl Doria         1.260513e+08
Nikko                9.178167e+07
                         ...
HON ARGATE           2.015995e+06
Michael Demeterio    2.000000e+06
Joshua Pineda        1.943000e+06
Vencian Diaz         1.834000e+06
Cesar Andes          1.588608e+06
Name: Price, Length: 295, dtype: float64

In [55]:
df.groupby('Author')['Price'].count().sort_values(ascending=False)

Author
Raimund               161
Patricia Marquez      114
Xian Jay Dimaano      107
Cherry Montefalcon     86
Mitch Razote           71
                     ...
Darryl Doria            1
La Chics TV             1
Dyana Macalino          1
Editha Vitug            1
Mary Ann                1
Name: Price, Length: 295, dtype: int64

## RQ 4 [needs visualization, comparative barplot]
Does nearby places of the condo affect its pricing?

Answer:

In [3]:
nearby_places = list(set(sum([x for x in df['Nearby Places']], [])))
len(nearby_places)

4

In [4]:
one_hot_encoded_np = df.copy()
for i in nearby_places:
    one_hot_encoded_np.insert(loc=len(one_hot_encoded_np.columns), column=i, value = 0)

In [5]:
for n_p in nearby_places:
    one_hot_encoded_np[n_p] = one_hot_encoded_np.apply(lambda x: 1 if n_p in x['Nearby Places'] else 0, axis=1)

In [6]:
# filter to condos, since only those has nearby places
one_hot_encoded_np = one_hot_encoded_np[one_hot_encoded_np['Type'] == 'Condo']

In [7]:
one_hot_encoded_np[nearby_places].sum().sort_values(ascending=False)

Hospital              1022
Mall                   984
School                 934
Transportation hub     834
dtype: int64

In [19]:
one_hot_encoded_np[one_hot_encoded_np['Price'] > np.mean(df['Price'])][nearby_places].sum().sort_values(ascending=False)

Hospital              177
Mall                  173
School                144
Transportation hub    138
dtype: int64

In [20]:
one_hot_encoded_np[df['Price'] < np.mean(df['Price'])][nearby_places].sum().sort_values(ascending=False)

C:\Users\chris\AppData\Local\Temp\ipykernel_40664\1157432718.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  one_hot_encoded_np[df['Price'] < np.mean(df['Price'])][nearby_places].sum().sort_values(ascending=False)

Hospital              845
Mall                  811
School                790
Transportation hub    696
dtype: int64

## RQ 5  [needs visualization]
What are the common features that exist on high-price range houses?

Answer:

### Filter High Prices (based on mean price)

In [88]:
high_prices = df[df['Price'] > np.mean(df['Price'])]
print(len(high_prices), '/', len(df))

AttributeError: 'str' object has no attribute 'mean'

### Features/Facilities [add visualization here, most prob barplot]

In [23]:
unique_features = list(set(sum([x for x in high_prices['Features']], [])))
unique_facilities = list(set(sum([x for x in high_prices['Facilities']], [])))
feature_facilities = list(set(unique_features + unique_facilities))
len(feature_facilities)

52

In [24]:
one_hot_encoded_ff = high_prices.copy()
for i in feature_facilities:
    one_hot_encoded_ff.insert(loc=len(one_hot_encoded_ff.columns), column=i, value = 0)

In [25]:
for ff in feature_facilities:
    one_hot_encoded_ff[ff] = one_hot_encoded_ff.apply(lambda x: 1 if ff in x['Features'] or ff in x['Facilities'] else 0, axis=1)

In [26]:
# Drop un-used columns
one_hot_encoded_ff = one_hot_encoded_ff.drop(columns =['Name', 'Address', 'Author', 'Price', 'Bedrooms', 'Showers', 'Parking', 'Furnish', 'Total Developed', 'Features', 'Facilities', 'Nearby Places', 'URL', 'Timestamp', 'NFeatures', 'NFacilities', 'NNearby Places'], axis=1)

In [44]:
one_hot_encoded_ff.groupby(['Type', 'City']).sum()

                     Hot Tub  Entertainment Area  Outdoor Area  Function Room  \
Type  City
Condo Cebu                 0                   0             0              1
      Makati               1                  28             2             40
      Malay                0                   0             0              0
      Mandaluyong          0                  16             0             16
      Manila               0                   7             0              9
      Muntinlupa           2                   3             3              3
      ParaÃ±aque            0                   0             0              1
      Pasay                0                   1             1              1
      Pasig                1                   3             4              8
      Quezon               0                   2             0              3
      San Juan             0                   0             0              6
      Taguig              12                  24            10             48
House Antipolo             0                   0             0              0
      Bacoor               0                   0             0              0
      Baguio               0                   0             0              0
      BiÃ±an                0                   0             0              0
      Carmona              0                   0             0              0
      Cebu                 0                   0             0              0
      Central Luzon        0                   0             0              0
      DasmariÃ±as           0                   0             0              0
      Imus                 0                   0             0              0
      Laguna               0                   0             0              0
      Lapu-Lapu            0                   0             0              0
      Las PiÃ±as            0                   0             0              0
      Makati               0                   0             0              0
      Mandaluyong          0                   0             0              0
      Manila               0                   0             0              0
      Marikina             0                   0             0              0
      Muntinlupa           0                   0             0              0
      ParaÃ±aque            0                   0             0              0
      Pasig                0                   0             0              0
      Quezon               0                   0             0              0
      San Juan             0                   0             0              0
      Santa Rosa           0                   0             0              0
      Silang               0                   0             0              0
      Tagaytay             0                   0             0              0
      Taguig               0                   0             0              0
      Taytay               0                   0             0              0
      Valencia             0                   0             0              0

                     CCTV  Building Reception Area  Laundry station  \
Type  City
Condo Cebu              2                        0                0
      Makati           34                       30                5
      Malay             0                        0                0
      Mandaluyong       6                        6                0
      Manila            3                        2                0
      Muntinlupa        0                        3                0
      ParaÃ±aque         0                        1                0
      Pasay             1                        1                1
      Pasig             5                        8                0
      Quezon            5                        6                0
      San Juan          3                        1                0
      Taguig           37                       42                2
House Antipolo          0                        0                0
      Bacoor            0                        0                0
      Baguio            0                        0                0
      BiÃ±an             0                        0                0
      Carmona           0                        0                0
      Cebu              0                        0                0
      Central Luzon     0                        0                0
      DasmariÃ±as        0                        0                0
      Imus              0                        0                0
      Laguna            0                        0                0
      Lapu-Lapu         0                        0                0
      Las PiÃ±as         0                        0                0
      Makati            0                        0                0
      Mandaluyong       0                        0                0
      Manila            0                        0                0
      Marikina          0                        0                0
      Muntinlupa        0                        0                0
      ParaÃ±aque         0                        0                0
      Pasig             0                        0                0
      Quezon            0                        0                0
      San Juan          0                        0                0
      Santa Rosa        0                        0                0
      Silang            0                        0                0
      Tagaytay          0                        0                0
      Taguig            0                        0                0
      Taytay            0                        0                0
      Valencia          0                        0                0

                     Clubhouse  Daycare  Gated  ...  Lounge  Court  Helipad  \
Type  City                                      ...
Condo Cebu                   0        0      0  ...       1      0        0
      Makati                 2        8      0  ...      18      9        9
      Malay                  0        0      0  ...       0      0        0
      Mandaluyong            1        1      0  ...       5      0        0
      Manila                 0        1      0  ...       3      0        0
      Muntinlupa             0        0      1  ...       1      0        0
      ParaÃ±aque              0        0      0  ...       1      0        0
      Pasay                  1        1      0  ...       1      0        0
      Pasig                  2        0      0  ...       8      0        0
      Quezon                 0        1      0  ...       3      1        0
      San Juan               0        0      0  ...       6      0        0
      Taguig                10        8      0  ...      46      6        0
House Antipolo               0        0      2  ...       0      0        0
      Bacoor                 0        0      4  ...       0      0        0
      Baguio                 0        0      1  ...       0      0        0
      BiÃ±an                  0        0      8  ...       0      0        0
      Carmona                0        0      0  ...       0      0        0
      Cebu                   0        0      4  ...       0      0        0
      Central Luzon          0        0      1  ...       0      0        0
      DasmariÃ±as             0        0      1  ...       0      0        0
      Imus                   0        0      1  ...       0      0        0
      Laguna                 0        0      0  ...       0      0        0
      Lapu-Lapu              0        0      1  ...       0      0        0
      Las PiÃ±as              0        0     24  ...       0      0        0
      Makati                 0        0      5  ...       0      0        0
      Mandaluyong            0        0      6  ...       0      0        0
      Manila                 0        0      5  ...       0      0        0
      Marikina               0        0      1  ...       0      0        0
      Muntinlupa             0        0     32  ...       0      0        0
      ParaÃ±aque              0        0     21  ...       0      0        0
      Pasig                  0        0     24  ...       0      0        0
      Quezon                 0        0     44  ...       0      0        0
      San Juan               0        0      3  ...       0      0        0
      Santa Rosa             0        0      2  ...       0      0        0
      Silang                 0        0      1  ...       0      0        0
      Tagaytay               0        0      2  ...       0      0        0
      Taguig                 0        0     15  ...       0      0        0
      Taytay                 0        0      1  ...       0      0        0
      Valencia               0        0      0  ...       0      0        0

                     Fitness Center  Play Area  Balcony  Roof Deck  Pool  \
Type  City
Condo Cebu                        2          0        1          1     2
      Makati                     61         34       20          2    63
      Malay                       0          0        0          0     0
      Mandaluyong                17         16       11          0    17
      Manila                      9          3        4          1     8
      Muntinlupa                  3          1        1          0     3
      ParaÃ±aque                   1          0        1          0     1
      Pasay                       1          2        2          0     2
      Pasig                       7          8        9          0    14
      Quezon                      7          5        5          1     6
      San Juan                    6          2        3          0     7
      Taguig                     66         43       36          1    77
House Antipolo                    0          0        4          0     2
      Bacoor                      0          0        3          0     6
      Baguio                      0          0        1          0     0
      BiÃ±an                       0          0        8          0     0
      Carmona                     0          0        0          0     0
      Cebu                        0          0        3          0     4
      Central Luzon               0          0        1          0     0
      DasmariÃ±as                  0          0        1          0     0
      Imus                        0          0        1          0     1
      Laguna                      0          0        0          0     0
      Lapu-Lapu                   0          0        2          0     3
      Las PiÃ±as                   0          0        7          0     8
      Makati                      0          0        2          0     1
      Mandaluyong                 0          0        0          0     0
      Manila                      0          0        0          0     1
      Marikina                    0          0        0          0     0
      Muntinlupa                  0          0       11          0    22
      ParaÃ±aque                   0          0       11          0     4
      Pasig                       0          0        3          0     4
      Quezon                      0          0       18          0    19
      San Juan                    0          0        2          0     1
      Santa Rosa                  0          0        0          0     2
      Silang                      0          0        2          0     0
      Tagaytay                    0          0        2          0     1
      Taguig                      0          0        5          0     0
      Taytay                      0          0        1          0     1
      Valencia                    0          0        0          0     0

                     Yoga Studio  WiFi
Type  City
Condo Cebu                     0     1
      Makati                   2     3
      Malay                    0     0
      Mandaluyong              4     3
      Manila                   0     0
      Muntinlupa               0     0
      ParaÃ±aque                0     0
      Pasay                    1     1
      Pasig                    6     3
      Quezon                   0     0
      San Juan                 0     0
      Taguig                   1     9
House Antipolo                 0     0
      Bacoor                   0     0
      Baguio                   0     1
      BiÃ±an                    0     0
      Carmona                  0     0
      Cebu                     0     0
      Central Luzon            0     1
      DasmariÃ±as               0     0
      Imus                     0     1
      Laguna                   0     0
      Lapu-Lapu                0     1
      Las PiÃ±as                0     4
      Makati                   0     1
      Mandaluyong              0     1
      Manila                   0     1
      Marikina                 0     0
      Muntinlupa               0     1
      ParaÃ±aque                0     1
      Pasig                    0     1
      Quezon                   0     0
      San Juan                 0     1
      Santa Rosa               0     2
      Silang                   0     0
      Tagaytay                 0     0
      Taguig                   0     0
      Taytay                   0     0
      Valencia                 0     0

[39 rows x 52 columns]

In [45]:
one_hot_encoded_ff.groupby(['Type', 'Region']).sum()

                                        Hot Tub  Entertainment Area  \
Type  Region
Condo Central Visayas                         0                   0
      National Capital Region                16                  84
      Western Visayas                         0                   0
House  Calabarzon                             0                   0
      Central Luzon                           0                   0
      Central Visayas                         0                   0
      Cordillera Administrative Region        0                   0
      National Capital Region                 0                   0
      Northern Mindanao                       0                   0

                                        Outdoor Area  Function Room  CCTV  \
Type  Region
Condo Central Visayas                              0              1     2
      National Capital Region                     20            135    94
      Western Visayas                              0              0     0
House  Calabarzon                                  0              0     0
      Central Luzon                                0              0     0
      Central Visayas                              0              0     0
      Cordillera Administrative Region             0              0     0
      National Capital Region                      0              0     0
      Northern Mindanao                            0              0     0

                                        Building Reception Area  \
Type  Region
Condo Central Visayas                                         0
      National Capital Region                               100
      Western Visayas                                         0
House  Calabarzon                                             0
      Central Luzon                                           0
      Central Visayas                                         0
      Cordillera Administrative Region                        0
      National Capital Region                                 0
      Northern Mindanao                                       0

                                        Laundry station  Clubhouse  Daycare  \
Type  Region
Condo Central Visayas                                 0          0        0
      National Capital Region                         8         16       20
      Western Visayas                                 0          0        0
House  Calabarzon                                     0          0        0
      Central Luzon                                   0          0        0
      Central Visayas                                 0          0        0
      Cordillera Administrative Region                0          0        0
      National Capital Region                         0          0        0
      Northern Mindanao                               0          0        0

                                        Gated  ...  Lounge  Court  Helipad  \
Type  Region                                   ...
Condo Central Visayas                       0  ...       1      0        0
      National Capital Region               1  ...      92     16        9
      Western Visayas                       0  ...       0      0        0
House  Calabarzon                          22  ...       0      0        0
      Central Luzon                         1  ...       0      0        0
      Central Visayas                       4  ...       0      0        0
      Cordillera Administrative Region      1  ...       0      0        0
      National Capital Region             181  ...       0      0        0
      Northern Mindanao                     0  ...       0      0        0

                                        Fitness Center  Play Area  Balcony  \
Type  Region
Condo Central Visayas                                2          0        1
      National Capital Region                      178        114       92
      Western Visayas                                0          0        0
House  Calabarzon                                    0          0       22
      Central Luzon                                  0          0        1
      Central Visayas                                0          0        3
      Cordillera Administrative Region               0          0        1
      National Capital Region                        0          0       61
      Northern Mindanao                              0          0        0

                                        Roof Deck  Pool  Yoga Studio  WiFi
Type  Region
Condo Central Visayas                           1     2            0     1
      National Capital Region                   5   198           14    19
      Western Visayas                           0     0            0     0
House  Calabarzon                               0    13            0     3
      Central Luzon                             0     0            0     1
      Central Visayas                           0     4            0     0
      Cordillera Administrative Region          0     0            0     1
      National Capital Region                   0    63            0    12
      Northern Mindanao                         0     0            0     0

[9 rows x 52 columns]

In [46]:
one_hot_encoded_ff.groupby(['Type', 'Island']).sum()

                Hot Tub  Entertainment Area  Outdoor Area  Function Room  \
Type  Island
Condo Luzon          16                  84            20            135
      Visayas         0                   0             0              1
House Luzon           0                   0             0              0
      Mindanao        0                   0             0              0
      Visayas         0                   0             0              0

                CCTV  Building Reception Area  Laundry station  Clubhouse  \
Type  Island
Condo Luzon       94                      100                8         16
      Visayas      2                        0                0          0
House Luzon        0                        0                0          0
      Mindanao     0                        0                0          0
      Visayas      0                        0                0          0

                Daycare  Gated  ...  Lounge  Court  Helipad  Fitness Center  \
Type  Island                    ...
Condo Luzon          20      1  ...      92     16        9             178
      Visayas         0      0  ...       1      0        0               2
House Luzon           0    205  ...       0      0        0               0
      Mindanao        0      0  ...       0      0        0               0
      Visayas         0      4  ...       0      0        0               0

                Play Area  Balcony  Roof Deck  Pool  Yoga Studio  WiFi
Type  Island
Condo Luzon           114       92          5   198           14    19
      Visayas           0        1          1     2            0     1
House Luzon             0       85          0    76            0    17
      Mindanao          0        0          0     0            0     0
      Visayas           0        3          0     4            0     0

[5 rows x 52 columns]

In [47]:
one_hot_encoded_ff[one_hot_encoded_ff['Type'] == 'Condo'].iloc[:, 4:].sum().sort_values(ascending=False)

Pool                        200
Fitness Center              180
Central air conditioning    177
Built-in wardrobes          160
Security                    149
Function Room               136
Stove/Burner                126
Ensuite                     122
Range Hood                  118
Play Area                   114
Floorboards                 111
Garden/Lanai                104
Building Reception Area     100
CCTV                         96
Lobby                        95
Lounge                       93
Balcony                      93
Maidâ€™s Room                  89
Entertainment Area           84
Utility Room                 65
Conference Room              47
Fiber ready                  46
Restaurants and/or Bars      39
Mailbox Area                 31
Co-working Space             31
Jogging Path                 30
Sauna                        26
Daycare                      20
Outdoor Area                 20
WiFi                         20
Retail Area                  16
Court                        16
Hot Tub                      16
Clubhouse                    16
Connected to mall            16
Yoga Studio                  14
Golf Course                  11
Garbage Chute                11
Club House                   10
Helipad                       9
Laundry station               8
Amenity Deck                  6
Roof Deck                     6
Gazebo                        4
Water Feature                 3
Pets Allowed                  2
Garage Space                  1
Maidâ€™s Quarters               1
Gated                         1
Fully Fenced                  1
Laundry Area                  1
Dirty Kitchen                 0
dtype: int64

In [48]:
one_hot_encoded_ff[one_hot_encoded_ff['Type'] == 'House'].iloc[:, 4:].sum().sort_values(ascending=False)

Garage Space                349
Garden/Lanai                242
Maidâ€™s Quarters             231
Fully Fenced                215
Gated                       209
Dirty Kitchen               166
Laundry Area                152
Balcony                      88
Pool                         80
Fiber ready                  56
WiFi                         17
Built-in wardrobes            1
Court                         0
Lounge                        0
Connected to mall             0
Conference Room               0
Water Feature                 0
Jogging Path                  0
Helipad                       0
Fitness Center                0
Play Area                     0
Roof Deck                     0
Pets Allowed                  0
Retail Area                   0
Garbage Chute                 0
Yoga Studio                   0
Maidâ€™s Room                   0
Hot Tub                       0
Range Hood                    0
Entertainment Area            0
Outdoor Area                  0
Function Room                 0
CCTV                          0
Building Reception Area       0
Laundry station               0
Clubhouse                     0
Daycare                       0
Central air conditioning      0
Co-working Space              0
Sauna                         0
Security                      0
Amenity Deck                  0
Mailbox Area                  0
Ensuite                       0
Stove/Burner                  0
Floorboards                   0
Restaurants and/or Bars       0
Lobby                         0
Gazebo                        0
Utility Room                  0
Club House                    0
Golf Course                   0
dtype: int64

In [49]:
one_hot_encoded_ff.iloc[:, 4:].sum().sort_values(ascending=False)

Garage Space                350
Garden/Lanai                346
Pool                        280
Maidâ€™s Quarters             232
Fully Fenced                216
Gated                       210
Balcony                     181
Fitness Center              180
Central air conditioning    177
Dirty Kitchen               166
Built-in wardrobes          161
Laundry Area                153
Security                    149
Function Room               136
Stove/Burner                126
Ensuite                     122
Range Hood                  118
Play Area                   114
Floorboards                 111
Fiber ready                 102
Building Reception Area     100
CCTV                         96
Lobby                        95
Lounge                       93
Maidâ€™s Room                  89
Entertainment Area           84
Utility Room                 65
Conference Room              47
Restaurants and/or Bars      39
WiFi                         37
Mailbox Area                 31
Co-working Space             31
Jogging Path                 30
Sauna                        26
Daycare                      20
Outdoor Area                 20
Court                        16
Hot Tub                      16
Retail Area                  16
Connected to mall            16
Clubhouse                    16
Yoga Studio                  14
Garbage Chute                11
Golf Course                  11
Club House                   10
Helipad                       9
Laundry station               8
Amenity Deck                  6
Roof Deck                     6
Gazebo                        4
Water Feature                 3
Pets Allowed                  2
dtype: int64

### Nearby Places [add visualization here, most prob barplot]

In [34]:
nearby_places = list(set(sum([x for x in high_prices['Nearby Places']], [])))
len(nearby_places)

4

In [35]:
one_hot_encoded_np = high_prices.copy()
for i in nearby_places:
    one_hot_encoded_np.insert(loc=len(one_hot_encoded_np.columns), column=i, value = 0)

In [36]:
for n_p in nearby_places:
    one_hot_encoded_np[n_p] = one_hot_encoded_np.apply(lambda x: 1 if n_p in x['Nearby Places'] else 0, axis=1)

In [37]:
# drop un-used columns
one_hot_encoded_np = one_hot_encoded_np.drop(columns =['Name', 'Address', 'Author', 'Price', 'Bedrooms', 'Showers', 'Parking', 'Furnish', 'Total Developed', 'Features', 'Facilities', 'Nearby Places', 'URL', 'Timestamp', 'NFeatures', 'NFacilities', 'NNearby Places'], axis=1)

In [38]:
# filter to condos, since only those has nearby places
one_hot_encoded_np = one_hot_encoded_np[one_hot_encoded_np['Type'] == 'Condo']

In [39]:
one_hot_encoded_np.groupby(['City']).sum()

             Mall  School  Transportation hub  Hospital
City
Cebu            1       1                   1         1
Makati         73      59                  54        73
Malay           0       0                   0         0
Mandaluyong    17      17                  17        17
Manila          2       2                   2         2
Muntinlupa      3       3                   3         3
ParaÃ±aque       0       0                   0         0
Pasay           1       0                   0         1
Pasig          10      14                  10        14
Quezon          2       1                   2         2
San Juan        6       6                   4         6
Taguig         58      41                  45        58

In [40]:
one_hot_encoded_np.groupby(['Region']).sum()

                         Mall  School  Transportation hub  Hospital
Region
Central Visayas             1       1                   1         1
National Capital Region   172     143                 137       176
Western Visayas             0       0                   0         0

In [41]:
one_hot_encoded_np.groupby(['Island']).sum()

         Mall  School  Transportation hub  Hospital
Island
Luzon     172     143                 137       176
Visayas     1       1                   1         1

In [42]:
one_hot_encoded_np[['Transportation hub', 'Mall', 'School', 'Hospital']].sum().sort_values(ascending=False)

Hospital              177
Mall                  173
School                144
Transportation hub    138
dtype: int64

## RQ 6  [needs visualization]
What is the average size of houses (in square meters) in a given area?

In [73]:
df.groupby(['Type', 'City'])['Total Developed'].mean().sort_values(ascending=False)

Type   City
House  Botolan               5000.000000
       Silang                 695.000000
       Muntinlupa             552.035714
       Quezon                 511.227586
       BiÃ±an                  460.500000
                                ...
Condo  San Jose Del Monte      23.000000
       Cagayan de Oro          22.666667
       Taytay                  22.000000
       BiÃ±an                   20.000000
       Alfonso                 15.000000
Name: Total Developed, Length: 103, dtype: float64

In [74]:
df.groupby(['Type', 'Region'])['Total Developed'].mean().sort_values(ascending=False)

Type   Region
House  National Capital Region             398.931741
       Northern Mindanao                   336.900000
       Cordillera Administrative Region    326.666667
       Central Visayas                     253.964706
        Calabarzon                         204.102407
       Central Luzon                       183.489362
Condo  Central Visayas                     107.894737
       National Capital Region              88.352155
       Cordillera Administrative Region     67.555556
       Western Visayas                      56.333333
        Calabarzon                          35.382817
        Ilocos Region                       27.500000
       Central Luzon                        25.625000
       Northern Mindanao                    22.666667
Name: Total Developed, dtype: float64

In [75]:
df.groupby(['Type', 'Island'])['Total Developed'].mean().sort_values(ascending=False)

Type   Island
House  Luzon       346.419286
       Mindanao    336.900000
       Visayas     253.964706
Condo  Visayas     100.863636
       Luzon        84.912340
       Mindanao     22.666667
Name: Total Developed, dtype: float64